export const cities = {
  '臺北市': { nationalNum: 0, items: [] },
  '新北市': { nationalNum: 0, items: [] },
  '基隆市': { nationalNum: 0, items: [] },
  '桃園市': { nationalNum: 0, items: [] },
  '新竹縣': { nationalNum: 0, items: [] },
  '新竹市': { nationalNum: 0, items: [] },
  '苗栗縣': { nationalNum: 0, items: [] },
  '臺中市': { nationalNum: 0, items: [] },
  '彰化縣': { nationalNum: 0, items: [] },
  '南投縣': { nationalNum: 0, items: [] },
  '雲林縣': { nationalNum: 0, items: [] },
  '嘉義縣': { nationalNum: 0, items: [] },
  '嘉義市': { nationalNum: 0, items: [] },
  '臺南市': { nationalNum: 0, items: [] },
  '高雄市': { nationalNum: 0, items: [] },
  '屏東縣': { nationalNum: 0, items: [] },
  '宜蘭縣': { nationalNum: 0, items: [] },
  '花蓮縣': { nationalNum: 0, items: [] },
  '臺東縣': { nationalNum: 0, items: [] },
  '澎湖縣': { nationalNum: 0, items: [] },
  '金門縣': { nationalNum: 0, items: [] },
  '連江縣': { nationalNum: 0, items: [] },
}

export const siteTypes = [
  { type: '宅第', num: 0, color: '#F2A074' },
  { type: '關塞', num: 0, color: '#EAA568' },
  { type: '寺廟', num: 0, color: '#DFAA5F' },
  { type: '城郭', num: 0, color: '#D0B05A' },
  { type: '祠堂', num: 0, color: '#C0B659' },
  { type: '衙署', num: 0, color: '#ADBB5E' },
  { type: '車站', num: 0, color: '#98C068' },
  { type: '書院', num: 0, color: '#82C376' },
  { type: '碑碣', num: 0, color: '#6BC687' },
  { type: '教堂', num: 0, color: '#52C89A' },
  { type: '牌坊', num: 0, color: '#39C8AF' },
  { type: '墓葬', num: 0, color: '#26C7C2' },
  { type: '堤閘', num: 0, color: '#2CC5D5' },
  { type: '產業', num: 0, color: '#49C1E3' },
  { type: '燈塔', num: 0, color: '#6CBCEE' },
  { type: '橋梁', num: 0, color: '#8FB5F3' },
  { type: '學校', num: 0, color: '#B2ACF2' },
  { type: '銀行', num: 0, color: '#D2A1EA' },
  { type: '其他設施', num: 0, color: '#EE96DD' },
]

export const noDataList = [
  '20180206000001',
  '20191128000001',
  '19881111000011',
  '19870417000002',
]